name: Waka Readme

on:
    push:
        branches:
            - master

jobs:
    update-readme:
        name: Update README.md
        runs-on: ubuntu-latest
        steps:
            - uses: athul/waka-readme@master
              with:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
